# **********************************************************
# Copyright (c) 2020-2023 Google, Inc.  All rights reserved.
# **********************************************************

# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of Google, Inc. nor the names of its contributors may be
#   used to endorse or promote products derived from this software without
#   specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL VMWARE, INC. OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
# DAMAGE.

# Github Actions workflow for Windows Continuous Integration testing.

# TODO i#2145: point at Qt5 for testing drgui build.

name: ci-windows
on:
  # Run on pushes to master and on pull request changes, including from a
  # forked repo with no "push" trigger, while avoiding duplicate triggers.
  push:

defaults:
  run:
    shell: cmd

jobs:
  ###########################################################################
  # 32-bit VS2019 and tests:
  vs2019-32:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true



    - name: Fetch Sources
      run: git fetch --no-tags --depth=1 origin master

    - name: Download Packages
      shell: powershell
      run: |
        md c:\projects\install
        (New-Object System.Net.WebClient).DownloadFile("https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-win.zip", "c:\projects\install\ninja.zip")
        (New-Object System.Net.WebClient).DownloadFile("https://sourceforge.net/projects/doxygen/files/rel-1.8.19/doxygen-1.8.19.windows.x64.bin.zip", "c:\projects\install\doxygen.zip")

    - name: Run Suite
      working-directory: ${{ github.workspace }}
      run: |
        mkdir -p dynamoriologs
        echo ------ Setting up paths ------
        7z x c:\projects\install\ninja.zip -oc:\projects\install\ninja > nul
        set PATH=c:\projects\install\ninja;%PATH%
        7z x c:\projects\install\doxygen.zip -oc:\projects\install\doxygen > nul
        set PATH=c:\projects\install\doxygen;%PATH%
        call "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars32.bat"
        echo ------ Running suite ------
        echo PATH is "%PATH%"
        echo Running in directory "%CD%"
        perl suite/runsuite_wrapper.pl automated_ci use_ninja 32_only debug_only
      env:
        CI_TRIGGER: ${{ github.event_name }}
        CI_BRANCH: ${{ github.ref }}


    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results-32-bit
        path: dynamoriologs/dynamorio-test-on-32-bit-win19.log

  ###########################################################################
  # 64-bit VS2019 and tests:
  vs2019-64:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true



    - name: Fetch Sources
      run: git fetch --no-tags --depth=1 origin master

    - name: Download Packages
      shell: powershell
      run: |
        md c:\projects\install
        (New-Object System.Net.WebClient).DownloadFile("https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-win.zip", "c:\projects\install\ninja.zip")
        (New-Object System.Net.WebClient).DownloadFile("https://sourceforge.net/projects/doxygen/files/rel-1.8.19/doxygen-1.8.19.windows.x64.bin.zip", "c:\projects\install\doxygen.zip")

    - name: Run Suite
      working-directory: ${{ github.workspace }}
      run: |
        mkdir -p dynamoriologs
        echo ------ Setting up paths ------
        7z x c:\projects\install\ninja.zip -oc:\projects\install\ninja > nul
        set PATH=c:\projects\install\ninja;%PATH%
        7z x c:\projects\install\doxygen.zip -oc:\projects\install\doxygen > nul
        set PATH=c:\projects\install\doxygen;%PATH%
        call "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars32.bat"
        echo ------ Running suite ------
        echo PATH is "%PATH%"
        echo Running in directory "%CD%"
        perl suite/runsuite_wrapper.pl automated_ci use_ninja 64_only debug_only
      env:
        CI_TRIGGER: ${{ github.event_name }}
        CI_BRANCH: ${{ github.ref }}


    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results-64-bit
        path: dynamoriologs/dynamorio-test-on-64-bit-win19.log

  ###########################################################################
  # 32-bit and 64-bit VS2019 release builds:
  vs2019-builds:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true


    - name: Fetch Sources
      run: git fetch --no-tags --depth=1 origin master

    - name: Download Packages
      shell: powershell
      run: |
        md c:\projects\install
        (New-Object System.Net.WebClient).DownloadFile("https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-win.zip", "c:\projects\install\ninja.zip")
        (New-Object System.Net.WebClient).DownloadFile("https://sourceforge.net/projects/doxygen/files/rel-1.8.19/doxygen-1.8.19.windows.x64.bin.zip", "c:\projects\install\doxygen.zip")

    - name: Run Suite
      working-directory: ${{ github.workspace }}
      run: |
        mkdir -p dynamoriologs
        echo ------ Setting up paths ------
        7z x c:\projects\install\ninja.zip -oc:\projects\install\ninja > nul
        set PATH=c:\projects\install\ninja;%PATH%
        7z x c:\projects\install\doxygen.zip -oc:\projects\install\doxygen > nul
        set PATH=c:\projects\install\doxygen;%PATH%
        call "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars32.bat"
        echo ------ Running suite ------
        echo PATH is "%PATH%"
        echo Running in directory "%CD%"
        perl suite/runsuite_wrapper.pl automated_ci use_ninja nontest_only
      env:
        CI_TRIGGER: ${{ github.event_name }}
        CI_BRANCH: ${{ github.ref }}
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results-release-builds
        path: dynamoriologs/dynamorio-test-on-release-win19.log

